using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using YourVRExperience.Utils;

namespace YourVRExperience.Game
{
    public class SystemEventGameController : SystemEventController
    {
        public const string EVENT_ENEMY_DEAD = "EVENT_ENEMY_DEAD";
        public const string EVENT_NPC_DEAD = "EVENT_NPC_DEAD";
        public const string EVENT_COIN_COLLECTED = "EVENT_COIN_COLLECTED";

        public const string EVENT_MOBILE_FIX_MOVEMENT = "EVENT_MOBILE_FIX_MOVEMENT";

        public const string EVENT_COMMAND_REENABLE_PHYSICS_AVATAR = "EVENT_COMMAND_REENABLE_PHYSICS_AVATAR";

        public const string EVENT_ITEM_COLLECTED = "EVENT_ITEM_COLLECTED";
        public const string EVENT_AVATAR_INITIAL_ANIMATION = "EVENT_AVATAR_INITIAL_ANIMATION";

        public const string EVENT_PLAYER_HAS_STARTED = "EVENT_PLAYER_HAS_STARTED";
        public const string EVENT_HUD_HAS_STARTED = "EVENT_HUD_HAS_STARTED";
        public const string EVENT_BULLET_HAS_STARTED = "EVENT_BULLET_HAS_STARTED";
        public const string EVENT_BULLET_HAS_BEEN_DESTROYED = "EVENT_BULLET_HAS_BEEN_DESTROYED";
        public const string EVENT_AREAVISIONDETECTED_HAS_STARTED = "EVENT_AREAVISIONDETECTED_HAS_STARTED";
        public const string EVENT_AREAVISIONDETECTED_HAS_BEEN_DESTROYED = "EVENT_AREAVISIONDETECTED_HAS_BEEN_DESTROYED";

        public const string EVENT_NETWORK_REPORT_NETWORK_ID = "EVENT_NETWORK_REPORT_NETWORK_ID";
        public const string EVENT_NETWORK_CHANGE_STATE = "EVENT_NETWORK_CHANGE_STATE";
        public const string EVENT_NETWORK_AVATAR_REQUEST_ANIMATION = "EVENT_NETWORK_AVATAR_REQUEST_ANIMATION";
        public const string EVENT_NETWORK_AVATAR_NEW_ANIMATION = "EVENT_NETWORK_AVATAR_NEW_ANIMATION";
        public const string EVENT_NETWORK_PLAYER_BULLET_SHOOT = "EVENT_NETWORK_PLAYER_BULLET_SHOOT";
        public const string EVENT_NETWORK_ENEMY_BULLET_SHOOT = "EVENT_NETWORK_ENEMY_BULLET_SHOOT";
        public const string EVENT_NETWORK_AVATAR_INITIAL_VALUES = "EVENT_NETWORK_AVATAR_INITIAL_VALUES";
        public const string EVENT_NETWORK_HAS_LOADED_THE_GAME = "EVENT_NETWORK_HAS_LOADED_THE_GAME";

        public const string EVENT_AVATAR_DESTROY_IT = "EVENT_AVATAR_DESTROY_IT";
        public const string EVENT_ENEMY_HAS_BEEN_STARTED = "EVENT_ENEMY_HAS_BEEN_STARTED";
        public const string EVENT_NPC_HAS_BEEN_STARTED = "EVENT_NPC_HAS_BEEN_STARTED";
        public const string EVENT_GAMECONTROLLER_PLAYER_HAS_BEEN_CONFIRMED = "EVENT_GAMECONTROLLER_PLAYER_HAS_BEEN_CONFIRMED";
    }
}